### ISSUE TITLE
Pawn activity always prioritize ZL going to unknown

### ISSUE THREAD

**Issue by MaysaChan** [RamRod6198/Z-Levels#60]
Every new game, my pawns will always set their activity to "ZL going to unknown" and they will travel to the left down corner of the map and it happening every few seconds make it impossible to task them to do anything at all.

**Comment by Taranchuk** [comment]
can you provide a save with this problem? and check the new version on the master if it fixes your problem

**Comment by MaysaChan** [comment]
Ah, thank you very much! the latest update fixed the issues now!
