### ISSUE TITLE
Screen blanks when loading Z-level

### ISSUE THREAD

**Issue by Rocksnotch** [RamRod6198/Z-Levels#61]
Whenever colonist tries to make a new z-level, even in new worlds, entire game screen grays over and I have to force-close the game to get out. All onscreen visuals are gone except nameplates of colonists.

**Comment by Taranchuk** [comment]
can you provide a save and hugslib log?

**Comment by Rocksnotch** [comment]
Sure! Here's the link to the uploaded hugslib log: https://gist.github.com/HugsLibRecordKeeper/a120357c0d433621fba085b03b5a886a

and attached in a zip is the save that contains a colonist a few seconds before trying to go down and generate a level...
[Autosave-5.zip](https://github.com/RamRod6198/Z-Levels/files/5221664/Autosave-5.zip)

**Comment by Rocksnotch** [comment]
...I wonder if its a problem with another mod I have? The load order didn't seem to change any of the issues.

**Comment by Taranchuk** [comment]
Your problem is RimThreaded mod, most likel
